### PR TITLE
vite: Fix HMR invalidation

### LINKED ISSUE #1481: [VITE] - vite-plugin of vanilla-extract is not updating CSS style after saving.
### Describe the bug

After initializing a new testing installation of Vite + React, and after following the basic guidelines for installing vanilla-extract, it seems that the vite-plugin is not updating the CSS when saving a new change in watch mode:

Screenshot 2024-09-30 211754

By swapping vite-plugin version on the package.json, I found that the issue is happening only when using "@vanilla-extract/vite-plugin": "4.0.13 - 14 -15"; while using "@vanilla-extract/vite-plugin": "4.0.12", the issue disappear and the plugin is working as intended.

### Reproduction

https://github.com/Darter90/react-vite-typescript-vanillaextract

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 18.53 GB / 31.71 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.52)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vanilla-extract/css: ^1.15.5 => 1.15.5
    @vanilla-extract/sprinkles: ^1.6.3 => 1.6.3
    @vanilla-extract/vite-plugin: 4.0.15 => 4.0.12
    vite: ^5.4.1 => 5.4.8
```

### Used Package Manager

npm

### Logs

_No response_

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by askoufis**
Fixes #1481.

#1438 broke HMR invalidation for files that don't end in `.css.ts`, e.g. `.css.tsx` which is a [valid](https://github.com/vanilla-extract-css/vanilla-extract/blob/d271b9f9e0e4f0bc668ded78bb15938627957a7a/packages/integration/src/filters.ts#L3), though uncommon, VE file extension.

This PR fixes this issue, as well as enables vite HMR for the `features` fixture to enable easier testing of HMR in the future.

### CODE REVIEW

File: fixtures/features/src/index.ts [hunk 1]
```diff
@@ -5,10 +5,3 @@ function render() {
 }
 
 render();
-
-// Uncomment to enable HMR with Vite
-// if (import.meta.hot) {
-//   import.meta.hot.accept('./features.css', () => {
-//     render();
-//   });
-// }
```
Comment (askoufis) [inline fixtures/features/src/index.ts:14]: This doesn't belong here anymore since this file no longer imports `features.css.ts`.

File: fixtures/features/src/html.ts [hunk 2]
```diff
@@ -10,3 +10,9 @@ export default `
     <div id="${testNodes.styleCompositionInSelector}" class="${styles.styleCompositionInSelector}">Style composition in selector</div>
     <div id="${testNodes.styleVariantsCompositionInSelector}" class="${styles.styleVariantsCompositionInSelector.variant}">Style variants composition in selector</div>
   `;
+
+// @ts-expect-error Vite env not defined
+if (import.meta.hot) {
+  // @ts-expect-error Vite env not defined
+  import.meta.hot.accept();
+}
```
Comment (askoufis) [inline fixtures/features/src/html.ts:18]: Self-accepting is fine here.
