### PR TITLE
Fix error when intializing next plugin

### LINKED ISSUE #1147: TypeError: Right-hand side of 'instanceof' is not an object with vanilla-extract/next-plugin@2.2.0
### Describe the bug

when I upgrade to `@vanilla-extract/next-plugin@v2.2.0` from `@vanilla-extract/next-plugin@v2.1.2`, `next dev` throws the below error log, and the process dies.

it's fixed when I downgrade to `@vanilla-extract/next-plugin@v2.1.3` again. because [the error line](https://github.com/vanilla-extract-css/vanilla-extract/pull/1105/files#diff-fe1f031aa9fe2619b9fa6c96c9879c91df7878306dded38a45ad67a55f067205R138) is newly added on #1105, which released on `@vanilla-extract/next-plugin@v2.2.0`.
image

~~not only yarn v1 but also npm occurred this issue. but pnpm was different.
when I create the next app with pnpm, install vanilla-extract, and run `pnpm run`, no more error logs are shown.~~ pnpm also got the same error.

### Reproduction

https://github.com/Sharlottes/reprod/

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   
    Memory: 2.18 GB / 15.87 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD  
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.10 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vanilla-extract/css: ^1.12.0 => 1.12.0 
    @vanilla-extract/next-plugin: ^2.2.0 => 2.2.0
```

### Used Package Manager

yarn

### Logs

```shell
user@DESKTOP-18FQSK1 MINGW64 ~/Documents/GitHub/Homepage (dev)
$ yarn dev
yarn run v1.22.19
$ next dev
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Right-hand side of 'instanceof' is not an object
    at C:\Users\user\Documents\GitHub\Homepage\node_modules\@vanilla-extract\next-plugin\dist\vanilla-extract-next-plugin.cjs.dev.js:109:47
    at Array.some (<anonymous>)
    at Object.webpack (C:\Users\user\Documents\GitHub\Homepage\node_modules\@vanilla-extract\next-plugin\dist\vanilla-extract-next-plugin.cjs.dev.js:109:25)
    at getBaseWebpackConfig (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\build\webpack-config.js:2147:32)
    at async Promise.all (index 2)
    at async Span.traceAsyncFn (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\trace\trace.js:103:20)
    at async Span.traceAsyncFn (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\trace\trace.js:103:20)
    at async HotReloader.start (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\server\dev\hot-reloader.js:573:30)
    at async DevServer.prepareImpl (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\server\dev\next-dev-server.js:685:9)
    at async NextServer.prepare (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\server\next.js:165:13)
    at async Server.<anonymous> (C:\Users\user\Documents\GitHub\Homepage\node_modules\next\dist\server\lib\render-server.js:136:17) {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by mattcompiles**
Fixes #1147

### CODE REVIEW

File: packages/next-plugin/src/index.ts [hunk 1]
```diff
@@ -2,17 +2,12 @@ import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
...
 import { lazyPostCSS } from 'next/dist/build/webpack/config/blocks/css';
 import { findPagesDir } from 'next/dist/lib/find-pages-dir';
-import nextMiniCssExtractPluginExports from 'next/dist/build/webpack/plugins/mini-css-extract-plugin';
+import NextMiniCssExtractPlugin from 'next/dist/build/webpack/plugins/mini-css-extract-plugin';
 
 import type webpack from 'webpack';
 import type { NextConfig } from 'next/types';
 import type { WebpackConfigContext } from 'next/dist/server/config-shared';
 
-// Next.js' built-in mini-css-extract-plugin has a very terrible type definition, let's just use any
```
Comment (mattcompiles) [inline packages/next-plugin/src/index.ts:11]: Looks like this was incorrect, I tested against next 12 and 13 and both worked with this change.

File: packages/next-plugin/src/index.ts [hunk 2]
```diff
@@ -2,17 +2,12 @@ import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
...
-const NextMiniCssExtractPlugin: any =
-  // @ts-expect-error -- Next.js' precompilation does add "__esModule: true", but doesn't add an actual default exports
```
Comment (mattcompiles) [inline packages/next-plugin/src/index.ts:13]: // Next.js' built-in mini-css-extract-plugin has a very terrible type definition, let's just use any

**Review by markdalgleish — APPROVED** [review]
